---
{{- if .Values.serviceMonitor.enabled }}
{{- if .Values.serviceMonitor.secret.createSecret.apikey }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "uptime-kuma.serviceMonitorSecret" . }}
  labels:
    {{- include "uptime-kuma.labels" . | nindent 4 }}
type: Opaque
data:
  username: {{ .Values.serviceMonitor.secret.createSecret.user | b64enc }}
  apikey: {{ .Values.serviceMonitor.secret.createSecret.apikey | b64enc }}
{{- end }}
{{- end }}