---
{{- if  .Values.serviceMonitor.enabled }}
apiVersion: apps/v1
kind: ServiceMonitor
metadata:
  name: {{ include "uptime-kuma.fullname" . }}
  labels:
    {{- include "uptime-kuma.labels" . | nindent 4 }}
spec:
  endpoints:
    - interval: {{ .Values.serviceMonitor.interval }}
      scheme: {{ .Values.serviceMonitor.scheme }}
      port: {{ .Values.serviceMonitor.port }}
      path: /metrics
      basicAuth:
        password:
          name: {{ include "uptime-kuma.serviceMonitorSecret" . }}
          key: apikey
        username:
          name: {{ include "uptime-kuma.serviceMonitorSecret" . }}
          key: username
  selector:
    matchLabels:
      {{- include "uptime-kuma.selectorLabels" . | nindent 6 }}
{{- end }}